<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="NLog" Version="6.0.3" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageVersion Include="HandyControl" Version="3.5.1" />
    <PackageVersion Include="YE.Control" Version="1.1.2025.816" />
  </ItemGroup>
</Project>