<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="LICENSE" />
  </ItemGroup>
  <ItemGroup>
	  <PackageReference Include="Serilog" />
	  <PackageReference Include="Serilog.Enrichers.Thread" />
	  <PackageReference Include="Serilog.Sinks.Console" />
	  <PackageReference Include="Serilog.Sinks.File" />
	  <PackageReference Include="CommunityToolkit.Mvvm" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	  <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
	  <PackageReference Include="YE.Control" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Solution Items\" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;$(SolutionDir).editorconfig&quot;  &quot;$(SolutionDir)WpfTemplate\Solution Items\&quot; &#xD;&#xA;copy &quot;$(SolutionDir).gitignore&quot;  &quot;$(SolutionDir)WpfTemplate\Solution Items\&quot; &#xD;&#xA;copy &quot;$(SolutionDir)Directory.Build.props&quot;  &quot;$(SolutionDir)WpfTemplate\Solution Items\&quot; &#xD;&#xA;copy &quot;$(SolutionDir)Directory.Packages.props&quot;  &quot;$(SolutionDir)WpfTemplate\Solution Items\&quot; &#xD;&#xA;copy &quot;$(SolutionDir)LICENSE&quot;  &quot;$(SolutionDir)WpfTemplate\Solution Items\&quot; &#xD;&#xA;copy &quot;$(SolutionDir)README.md&quot;  &quot;$(SolutionDir)WpfTemplate\Solution Items\&quot; " />
  </Target>
</Project>